---
- hosts: local
  remote_user: ec2-user
  become: true
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=installed
  - name: copy index file
    copy: src=/home/ec2-user/files/index.html dest=/var/www/html/index.html
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
