---
- hosts: local
  remote_user: ec2-user
  become: true
  vars:
    http_port: 8000
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest

  - name: copy index file
    copy: src=/home/ec2-user/files/index.html dest=/var/www/html/index.html

  - name: write the apache config file
    template: src=//home/ec2-user/templates/httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
    - restart apache

  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
