---
- hosts: local
  remote_user: ec2-user
  become: true
  vars:
    http_port: 80

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write the apache config file
    template:
      src: /home/ec2-user/templates/httpd.conf.j2
      dest: /etc/http/conf/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
